import Footer from '@/components/layout/footer'
import Nav from '@/components/layout/nav'
import '@/lib/styles/css/index.css'
import { fontsVariable } from '@/lib/styles/fonts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" dir="ltr" className={fontsVariable}>
      <body>
        <div className="layout-grid">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
