import type { Metadata } from 'next'
import '@/lib/styles/css/index.css'
import { fontsVariable } from '@/lib/styles/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" dir="ltr" className={fontsVariable}>
      <body>{children}</body>
    </html>
  )
}
